### ISSUE TITLE
An error occurred (ParameterNotFound) when calling the GetParameter operation:

### ISSUE THREAD

**Issue by s1mrankaur** [awslabs/aws-simple-cicd#10]
In the build phase of the code pipeline, in SemverLambda, on line 119, I get an error "Parameter not found"

```
[
  | 2020-11-12T14:43:48.264-08:00Copy{'repo': 'test', 'branch': 'master'} | {'repo': 'test', 'branch': 'master'}
-- | -- | --
  | 2020-11-12T14:43:48.407-08:00CopyFunction failed due to exception. | Function failed due to exception.
  | 2020-11-12T14:43:48.407-08:00CopyAn error occurred (ParameterNotFound) when calling the GetParameter operation: | An error occurred (ParameterNotFound) when calling the GetParameter operation:
  | 2020-11-12T14:43:48.407-08:00 | Traceback (most recent call last):
  | 2020-11-12T14:43:48.407-08:00 | File "/var/task/lambda.py", line 119, in semver_handler
  | 2020-11-12T14:43:48.407-08:00 | response = ssm.get_parameter(
  | 2020-11-12T14:43:48.407-08:00 | File "/var/runtime/botocore/client.py", line 316, in _api_call

]
```
   line 118 need to change to
   
`   ssm_param = ssm_root + '/' +  repo + '/' + branch + '/version'
`  
    from 

`   ssm_param = ssm_root + '/codecommit/' + repo + '/' + branch + '/version'
`

to resolve the issue

**Comment by srijitm** [comment]
Did you set the repo type in project-config.json?

**Comment by s1mrankaur** [comment]
I did @srijitm  The only way to resolve this was remove '/codecommit'/ form the ssm_param.

**Comment by srijitm** [comment]
Ok, thank you very much for opening this bug. I'll assign it to myself.
