### ISSUE TITLE
Long time to deploy the pipeline

### ISSUE THREAD

**Issue by s1mrankaur** [awslabs/aws-simple-cicd#60]
It takes a fairly long time (About 6-8 minutes( to deploy on making a change of 1 line of code as well. Is there a way around it?

**Comment by srijitm** [comment]
@s1mrankaur Is that for the entire pipeline or just the deploy stage? 

A couple of things you can look at:
- assign more CPU/Memory to the CodeBuild job: https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-compute-types.html

**Comment by s1mrankaur** [comment]
@srijitm  Deploy stage: The command I am running is:

`cdk deploy --all --profile profile-name`

**Comment by srijitm** [comment]
Remove the --all and include only the stack you want to deploy.

**Comment by s1mrankaur** [comment]
@srijitm  Is there a way for it to automatically detect what stack should be deployed?

**Comment by srijitm** [comment]
No. 

Cloudformation (and therefore CDK) only pushes the changes anyways. However, it may take some time for it to do the diff.

**Comment by s1mrankaur** [comment]
That explains it. Thank you

**Comment by s1mrankaur** [comment]
Also, I have a question related to issue https://github.com/awslabs/aws-simple-cicd/issues/61 . Does npm install command need to be run in all the scripts i.e build.sh, deploy.sh and test.sh ? lerna run commands seem to be running okay in build.sh where the npm install command runs but throws MODULE_NOT_FOUND errr in deploy.sh and test.sh @srijitm

**Comment by srijitm** [comment]
You should take a look and see if everything is being packaged correctly (can probably run the `ls -al` command to check). Also take a look at how lerna includes the node_modules (whether they are symlinks, relative links etc). Fully qualified symlinks will likely not work because the CODEBUILD_SRC_DIR changes between the stages. Running `npm install` might be the easiest thing to do but that will increase execution time.

**Comment by s1mrankaur** [comment]
@srijitm I did run npm install in test.sh as well,

but it still failed. while the same command runs just fine in build.sh

So here's what my build.sh looks like:

```
#! /bin/bash

set -e
set -u
set -o pipefail

echo "Building services..................!"
npm install
npm run test
echo "Build completed..................!"
```

Here's what my test.sh looks like:


```
#! /bin/bash

set -e
set -u
set -o pipefail

echo "Running tests...........................!"
npm install
npm run test
echo "Tests completed.........................!"
```

The build stage completed okay, and the test stage throws this error:

```

> backend@0.1.0 postinstall
--
66 | > lerna bootstrap
67 |  
68 | internal/modules/cjs/loader.js:834
69 | throw err;
70 | ^
71 |  
72 | Error: Cannot find module '.'
73 | Require stack:
74 | - /codebuild/output/src188079499/src/node_modules/.bin/lerna
75 | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
76 | at Function.Module._load (internal/modules/cjs/loader.js:687:27)
77 | at Module.require (internal/modules/cjs/loader.js:903:19)
78 | at require (internal/modules/cjs/helpers.js:74:18)
79 | at Object.<anonymous> (/codebuild/output/src188079499/src/node_modules/.bin/lerna:11:3)
80 | at Module._compile (internal/modules/cjs/loader.js:1015:30)
81 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
82 | at Module.load (internal/modules/cjs/loader.js:879:32)
83 | at Function.Module._load (internal/modules/cjs/loader.js:724:14)
84 | at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
85 | code: 'MODULE_NOT_FOUND',
86 | requireStack: [ '/codebuild/output/src188079499/src/node_modules/.bin/lerna' ]
87 | }
88 | npm ERR! code 1
89 | npm ERR! path /codebuild/output/src188079499/src
90 | npm ERR! command failed
91 | npm ERR! command sh -c lerna bootstrap
92 |  
93 | npm ERR! A complete log of this run can be found in:
94 | npm ERR!     /root/.npm/_logs/2021-03-15T23_15_26_005Z-debug.log
95 |  
96 | [Container] 2021/03/15 23:15:26 Command did not exit successfully bash ${CODEBUILD_SRC_DIR}/scripts/test.sh exit status 1
97 | [Container] 2021/03/15 23:15:26 Phase complete: BUILD State: FAILED
98 | [Container] 2021/03/15 23:15:26 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: bash ${CODEBUILD_SRC_DIR}/scripts/test.sh. Reason: exit status 1
99 | [Container] 2021/03/15 23:15:26 Entering phase POST_BUILD
100 | [Container] 2021/03/15 23:15:26 Phase complete: POST_BUILD State: SUCCEEDED
101 | [Container] 2021/03/15 23:15:26 Phase context status code:  Message:
102 | [Container] 2021/03/15 23:15:26 Expanding base directory path: .
103 | [Container] 2021/03/15 23:15:26 Assembling file list
104 | [Container] 2021/03/15 23:15:26 Expanding .
105 | [Container] 2021/03/15 23:15:26 Expanding file paths for base directory .
106 | [Container] 2021/03/15 23:15:26 Assembling file list
107 | [Container] 2021/03/15 23:15:26 Expanding **/*
108 | [Container] 2021/03/15 23:15:26 Found 34591 file(s)
109 | [Container] 2021/03/15 23:15:35 Phase complete: UPLOAD_ARTIFACTS State: SUCCEEDED
110 | [Container] 2021/03/15 23:15:35 Phase context status code:  Message:
111 |  



```

@srijitm

**Comment by s1mrankaur** [comment]
@srijitm  If it's relevant,  I needed the pipeline to use node runtime 15, so I had added following in 

1.tets-project.js
2. deploy-project.ts
3. build-project.ts
```

          install: {
            commands: [
              'npm install npm@latest -g',
              'npm install lerna@latest -g'
            ]
          },
```

and removed:
```

        phases: {
          install: {
            'runtime-versions': {
              nodejs: '10'
            }
          },

Please let me know if that's not right or could be causing the issue. 


```
